name: Release

on:
  push:
    tags:
      - "*"
    branches:
      - "dev"

permissions:
  contents: write
jobs:
  submit:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Zip extensions
        run: |
          bun run zip
          bun run zip:edge

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .output/*-chrome.zip
            .output/*-edge.zip
