name: Release

on:
    
  push:
    tags:
      - "*"
  
permissions: 
  contents: write
jobs:
  submit:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
  

      - name: Install dependencies
        run: npm install
        

      - name: Zip extensions
        run: |
          npm run zip
          npm run zip:edge
        
  
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .output/*-chrome.zip
            .output/*-edge.zip

